version: '3'
services:
  mysql:
    image: mysql
    
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: "Mizdooni"

  spring-boot-app:
      image: mizdooni-back
      ports:
        - "8083:8083"
      depends_on:
        - mysql