version: '3'
services:
  mysql:
    image: mysql
    
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234

  spring-boot-app:
      image: mizdooni-back
      ports:
        - "8080:8080"
      depends_on:
        - mysql