version: '3'
services:
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      # MYSQL_USER: product_user
      MYSQL_PASSWORD: 1234
      # MYSQL_DATABASE: product

  spring-boot-app:
      build:
        context: ./backend
        dockerfile: Dockerfile
      ports:
        - "8083:8083"
      depends_on:
        - mysql
      # environment:
      #   SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/product
      #   SPRING_DATASOURCE_USERNAME: product_user
      #   SPRING_DATASOURCE_PASSWORD: product_user_password

  react-app:
      build:
        context: ./frontend
        dockerfile: Dockerfile
      ports:
        - "8998:3000"
